Resources:
    PackBinariesProject:
      Type: "AWS::CodeBuild::Project"
      Properties:
        ServiceRole: '{{resolve:ssm:zworker_codebuild_role_arn:1}}'
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: "LINUX_CONTAINER"
          ComputeType: "BUILD_GENERAL1_SMALL"
          Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
          ImagePullCredentialsType: "CODEBUILD"
          PrivilegedMode: false
          EnvironmentVariables:
            - 
              Name: "ACCOUNT_ROLE_ARN"
              Type: "PARAMETER_STORE"
              Value: "zworker_development_cloudformation_role_arn"
            - 
              Name: "STAGE"
              Type: "PARAMETER_STORE"
              Value: "/zworker/DEV_STAGE"
            - 
              Name: "REGION"
              Type: "PARAMETER_STORE"
              Value: "/zworker/DEV_REGION"
        LogsConfig:
          CloudWatchLogs:
            Status: "ENABLED"
        Source:
          Type: "CODEPIPELINE"
          InsecureSsl: false
          BuildSpec: "buildspec.yml"
    
    zWorkerBinaryPipeline: 
      Type: "AWS::CodePipeline::Pipeline"
      Properties: 
        RoleArn: '{{resolve:ssm:zworker_pipeline_role_arn:3}}'
        ArtifactStore: 
          Type: S3 
          Location: '{{resolve:ssm:zworker_pipeline_bucket_name:2}}'
          EncryptionKey:
            Type: KMS
            Id: '{{resolve:ssm:zworker_pipeline_kms_key_arn:3}}'
        Stages:
          - Name: Source
            Actions:
              - Name: Source1
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Version: "1"
                  Provider: GitHub
                Namespace: SourceVariables
                OutputArtifacts:
                  - Name: SourceArtifact
                Configuration:
                  Owner: 'priyanshu'
                  Repo: 'pack-lambda-layer'
                  Branch: 'main'
                  OAuthToken: '{{resolve:secretsmanager:ZWORKER_GITHUB:SecretString:zworkerGithubAccessToken}}'
                RunOrder: 1
    
          - Name: "SelfUpdateBuild"
            Actions:
            - Name: "SelfUpdateStack"
              InputArtifacts: 
                - Name: "SourceArtifact"
              OutputArtifacts:
                - Name: "SelfUpdateArtifact"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              RunOrder: 1
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                StackName: !Ref AWS::StackName
                RoleArn: '{{resolve:ssm:zworker_pipeline_role_arn:3}}'
                TemplatePath: SourceArtifact::codepipeline/resources/template/template.yml
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
          
          - Name: "TestBuild"
            Actions:
            - Name: "TestBuild"
              InputArtifacts: 
                - Name: "SourceArtifact"
              OutputArtifacts:
                - Name: "TestArtifact"
              ActionTypeId:
                Version: '1'
                Owner: "AWS"
                Category: "Build"
                Provider: "CodeBuild"
              RunOrder: 1
              Configuration:
                ProjectName: !Ref PackBinariesProject
