version: 0.2

phases:
  pre_build:
    commands:
      - mkdir efs
      - yum install -y amazon-efs-utils
      # - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 10.0.54.155:/ efs
      - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${EFS_MOUNT_IP}:/ efs
      - cd efs
      - ls
      - rm -rf *
      - cd ../
      - yum install -y amazon-linux-extras
      - yum -y install openjpeg-devel libjpeg-devel fontconfig-devel libtiff-devel libpng-devel xz gcc gcc-c++ epel-release zip cmake3 hunspell-devel python38-devel poppler-utils poppler-cpp-devel make autoconf aclocal automake libtool libjpeg-devel libpng-devel libtiff-devel zlib-devel ibzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel ImageMagick ImageMagick-devel
      - yum -y groupinstall "Development Tools"
      - ln -s /usr/libexec/gcc/x86_64-amazon-linux/4.8.5/cc1plus /usr/local/bin/
      - ln -s /usr/lib64/libhunspell-1.3.so /usr/lib64/libhunspell.so
      - ls
      - python -m pip install pipenv
      - pipenv install
      - cp -r $(pipenv --venv)/ efs
      - cp buildspec.yml efs
      - cd efs
      - ls
      - cd ../

  build:
    commands:
      - python --version 
      - echo "Done!"
